theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "underline"
normal = "underline"
select = "underline"

[editor.indent-guides]
render = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true
